Repository ocaml-dune/binary-distribution, pull requests merged in 2024-10, with the labels that each got.

#49 feat: support new dune.build URLs
  Dockerfile
  install
  sandworm/bin/config.ml
  sandworm/bin/main.ml
  sandworm/lib/rclone.ml
  sandworm/lib/web.mlx
Labels: enhancement, Web, Pipeline

#50 Fix some wording
  sandworm/lib/web.mlx
Labels: bug, Web

#52 fix: bot notify on branch main failure
  .github/workflows/binary.yaml
Labels: bug, enhancement

#48 feat: build and use tarballs on install
  .github/workflows/binary.yaml
  install
Labels: enhancement, pipeline

#57 More secure curl options
  sandworm/lib/web.mlx
Labels: web

#58 fix: restore to valid mlx
  sandworm/lib/web.mlx
Labels: bug, web

#59 `dune.ci.dev` -> `preview.dune.build`
  README.md
  docs/pipeline.svg
  index.html
  sandworm/lib/web.mlx
Labels: bug, web

#62 Apply some shellcheck improvements
  install
Labels: enhancement

#71 Readable colours on dark terminals
  static/install
Labels: bug, script

#75 fix: don't try to push index.html
  .github/workflows/binary.yaml
Labels: bug, pipeline

#67 Make the install script POSIX compatible
  lib/web.mlx
  static/install
Labels: enhancement, script

#61 feat: implement the new design
  css/style.css
  lib/core.ml
  lib/icons.mlx
  lib/metadata.ml
  lib/web.mlx
  static/dune_favicon.png
  static/img_camel_hero_banner.png
  static/main.css
  tailwind.config.js
Labels: DO-NOT-MERGE, web

#77 feat: complete the design for desktop version
  lib/icons.mlx
  lib/web.mlx
  static/main.css
Labels: enhancement, web

#82 Improve the wording
  lib/web.mlx
Labels: web

#83 fix: push the script to the root location
  bin/main.ml
Labels: bug, pipeline, script

#89 feat: use latest to redirect to correct URL
  bin/server.ml
Labels: enhancement, web, script

#91 chore: update authors and maintainers
  dune-project
  sandworm.opam
Labels: docs

#92 Add links to the package management documentation
  lib/web.mlx
Labels: web

#95 fix: check_build action
  .github/workflows/binary.yaml
Labels: bug, pipeline

#97 fix: add links and clean typos
  lib/icons.mlx
  lib/web.mlx
Labels: web

#99 fix: temporary deactivate the duplication check
  .github/workflows/binary.yaml
Labels: bug, pipeline, script

#104 Fix FAQ typo
  lib/web.mlx
Labels: web

#103 Enable prettyprinting of the generated JSON
  lib/metadata.ml
Labels: enhancement, pipeline

#90 feat: error handling
  bin/main.ml
  bin/server.ml
  lib/web.mlx
  static/main.css
Labels: bug, web

#109 chore(ci): reactivate build on change feature
  .github/workflows/binary.yaml
Labels: hack, pipeline

#111 chore: staging use a subdir for test
  .github/workflows/binary.yaml
  README.md
Labels: enhancement, pipeline, script

#68 Don't update the shell rc if it's already been updated by a previous installation (and add completion scripts)
  .github/workflows/binary.yaml
  completions/bash.sh
  env/env.bash
  env/env.fish
  env/env.zsh
Labels: bug, enhancement, script

#116 feat: build on workflow dispatch event
  .github/workflows/binary.yaml
Labels: enhancement, pipeline

#108 Create temporary directory in temporary location
  static/install
Labels: script
