Repository ocaml-dune/binary-distribution, pull requests merged in 2024-11, with the labels that each got.

#119 Update completion script
  completions/bash.sh
Labels: enhancement, script

#118 fix: add hover effects
  lib/icons.mlx
  lib/web.mlx
  static/main.css
Labels: bug, web

#117 Download and unpack opam-repo revision store cache
  static/install
Labels: enhancement, script

#123 Extract archives as the current user instead of the archive user
  static/install
Labels: script

#127 Fix GitHub link
  lib/web.mlx
Labels: bug, web

#128 No need to enable toolchains anymore on recent builds
  lib/web.mlx
Labels: web

#136 Use more restrictive options to make `curl` safer
  static/install
Labels: script

#138 fix: stop uploading executables
  .github/workflows/binary.yaml
Labels: hack, pipeline, script

#137 feat: make the getting started clearer
  lib/web.mlx
Labels: web
